
# initializing list. populate list with items to randomize
games = [
    "A Way Out",
    "It Takes Two",
    "Diablo IV",
    "Dying Light",
    "No Man's Sky",
    "Devil May Cry V",
    "Grand Theft Auto V",
    "Nex-Machina",
    "Red Dead Redemption II",
    "Killing Floor 2",
    "Ultimate Fishing Simulator",
    "Valorant",
    "Leage Of Legends",
    "Rocket League",
    "Sea of Thieves",
    "Battle Rock Galactica",
    "Ultimate Chicken Horse",
    "Teenage Mutant Ninja Turtles: Shredder's Revenge",
    "Scrap Mechanic",
    "My Time at Sandrock",
    "Among Us",
    "Apex Legends",
    "Battleblock Theater",
    "Borderlands 2",
    "Borderlands 3",
    "Call of Duty Warzone",
    "Castle Crashers",
    "Dead By Daylight",
    "Dragonball FighterZ",
    "Farming Simulator 15",
    "Forts",
    "Gang Beasts",
    "Golf It",
    "Golf With Your Friends",
    "Jackbox Party Pack",
    "Keep Talking and Nobody Explodes",
    "Left 4 Dead 2",
    "Lethal League",
    "Lovers In A Dangerous Spacetime",
    "Monaco",
    "Monster Hunter World",
    "Mortal Kombat",
    "Mount Your Friends",
    "Overcooked",
    "Payday 2",
    "Portal 2",
    "Player Unknown's Battlegrounds",
    "Pummel Party",
    "Scott Pilgrim Vs The World",
    "Sniper Elite Nazi Zombie Army",
    "State of Decay 2",
    "Tabletop Simulator",
    "Splinter Cell Blacklist",
    "Street Fighter 5",
    "Uno",
    "Vampire Survivors",
    "Worms Clan Wars",
    "Zombie Army Trilogy"]
 