restaurants = [
    "Mario's Pizza",
    "Mariscos El Parisol",
    "Nik's Not Normal",
    "Panera",
    "Taco Palenque",
    "Dog Haus",
    "Olive Garden",
    "Chili's",
    "Lupe Tortilla",
    "Taj Mahal",
    "Thai Lao",
    "Chester's",
    "Willie's",
    "Longhorn Steakhouse",
    "The Branch Neighborhood Grill",
    ]